# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InterfaceDesign.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!
"""This is the python code generated from the ui file of my GUI, it needs an in-between before it can connect with
    the code. The in-between file is UiToCode.py"""

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 605)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.appTabs = QtWidgets.QTabWidget(self.centralwidget)
        self.appTabs.setGeometry(QtCore.QRect(0, 0, 801, 581))
        self.appTabs.setAutoFillBackground(False)
        self.appTabs.setObjectName("appTabs")
        self.tabMaster = QtWidgets.QWidget()
        self.tabMaster.setObjectName("tabMaster")
        self.mArpL = QtWidgets.QLabel(self.tabMaster)
        self.mArpL.setGeometry(QtCore.QRect(10, 80, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.mArpL.setFont(font)
        self.mArpL.setObjectName("mArpL")
        self.mDNSL = QtWidgets.QLabel(self.tabMaster)
        self.mDNSL.setGeometry(QtCore.QRect(420, 80, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.mDNSL.setFont(font)
        self.mDNSL.setObjectName("mDNSL")
        self.mDNSC = QtWidgets.QPushButton(self.tabMaster)
        self.mDNSC.setGeometry(QtCore.QRect(690, 500, 101, 41))
        self.mDNSC.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mDNSC.setObjectName("mDNSC")
        self.mARPC = QtWidgets.QPushButton(self.tabMaster)
        self.mARPC.setGeometry(QtCore.QRect(280, 500, 101, 41))
        self.mARPC.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.mARPC.setObjectName("mARPC")
        self.mARPD = QtWidgets.QTextEdit(self.tabMaster)
        self.mARPD.setGeometry(QtCore.QRect(0, 120, 381, 371))
        self.mARPD.setObjectName("mARPD")
        self.mDNSD = QtWidgets.QTextEdit(self.tabMaster)
        self.mDNSD.setGeometry(QtCore.QRect(410, 120, 381, 371))
        self.mDNSD.setObjectName("mDNSD")
        self.appTabs.addTab(self.tabMaster, "")
        self.tabARP = QtWidgets.QWidget()
        self.tabARP.setObjectName("tabARP")
        self.arpDetect = QtWidgets.QPushButton(self.tabARP)
        self.arpDetect.setGeometry(QtCore.QRect(20, 480, 101, 41))
        self.arpDetect.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.arpDetect.setObjectName("arpDetect")
        self.arpTitle = QtWidgets.QLabel(self.tabARP)
        self.arpTitle.setGeometry(QtCore.QRect(10, 10, 341, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.arpTitle.setFont(font)
        self.arpTitle.setWordWrap(True)
        self.arpTitle.setObjectName("arpTitle")
        self.arpExplain = QtWidgets.QLabel(self.tabARP)
        self.arpExplain.setGeometry(QtCore.QRect(10, 70, 271, 191))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.arpExplain.setFont(font)
        self.arpExplain.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.arpExplain.setWordWrap(True)
        self.arpExplain.setObjectName("arpExplain")
        self.arpEnd = QtWidgets.QPushButton(self.tabARP)
        self.arpEnd.setGeometry(QtCore.QRect(180, 480, 101, 41))
        self.arpEnd.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.arpEnd.setObjectName("arpEnd")
        self.arpClear = QtWidgets.QPushButton(self.tabARP)
        self.arpClear.setGeometry(QtCore.QRect(350, 480, 101, 41))
        self.arpClear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.arpClear.setObjectName("arpClear")
        self.arpDisplay = QtWidgets.QTextEdit(self.tabARP)
        self.arpDisplay.setGeometry(QtCore.QRect(470, 20, 321, 501))
        self.arpDisplay.setObjectName("arpDisplay")
        self.appTabs.addTab(self.tabARP, "")
        self.tabDNS = QtWidgets.QWidget()
        self.tabDNS.setObjectName("tabDNS")
        self.dnsTitle = QtWidgets.QLabel(self.tabDNS)
        self.dnsTitle.setGeometry(QtCore.QRect(10, 10, 341, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        self.dnsTitle.setFont(font)
        self.dnsTitle.setWordWrap(True)
        self.dnsTitle.setObjectName("dnsTitle")
        self.dnsExplain = QtWidgets.QLabel(self.tabDNS)
        self.dnsExplain.setGeometry(QtCore.QRect(10, 70, 271, 191))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.dnsExplain.setFont(font)
        self.dnsExplain.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.dnsExplain.setWordWrap(True)
        self.dnsExplain.setObjectName("dnsExplain")
        self.dnsDetect = QtWidgets.QPushButton(self.tabDNS)
        self.dnsDetect.setGeometry(QtCore.QRect(20, 480, 101, 41))
        self.dnsDetect.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dnsDetect.setObjectName("dnsDetect")
        self.dnsClear = QtWidgets.QPushButton(self.tabDNS)
        self.dnsClear.setGeometry(QtCore.QRect(350, 480, 101, 41))
        self.dnsClear.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dnsClear.setObjectName("dnsClear")
        self.dnsEnd = QtWidgets.QPushButton(self.tabDNS)
        self.dnsEnd.setGeometry(QtCore.QRect(180, 480, 101, 41))
        self.dnsEnd.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dnsEnd.setObjectName("dnsEnd")
        self.dnsDisplay = QtWidgets.QTextEdit(self.tabDNS)
        self.dnsDisplay.setGeometry(QtCore.QRect(470, 20, 321, 501))
        self.dnsDisplay.setObjectName("dnsDisplay")
        self.appTabs.addTab(self.tabDNS, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.appTabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.mArpL.setText(_translate("MainWindow", "ARP Detection"))
        self.mDNSL.setText(_translate("MainWindow", "DNS Detection"))
        self.mDNSC.setText(_translate("MainWindow", "Clear"))
        self.mARPC.setText(_translate("MainWindow", "Clear"))
        self.appTabs.setTabText(self.appTabs.indexOf(self.tabMaster), _translate("MainWindow", "Master Page"))
        self.arpDetect.setText(_translate("MainWindow", "Initiate"))
        self.arpTitle.setText(_translate("MainWindow", "ARP Detection Module"))
        self.arpExplain.setText(_translate("MainWindow", "This module deals with detection of ARP attacks and displays a message if an attack is detected. To use this module you click on the initiate button below."))
        self.arpEnd.setText(_translate("MainWindow", "End"))
        self.arpClear.setText(_translate("MainWindow", "Clear"))
        self.appTabs.setTabText(self.appTabs.indexOf(self.tabARP), _translate("MainWindow", "ARP"))
        self.dnsTitle.setText(_translate("MainWindow", "DNS Detection Module"))
        self.dnsExplain.setText(_translate("MainWindow", "This module deals with detection of DNS attacks and displays a message if an attack is detected. To use this module you click on the initiate button below."))
        self.dnsDetect.setText(_translate("MainWindow", "Initiate"))
        self.dnsClear.setText(_translate("MainWindow", "Clear"))
        self.dnsEnd.setText(_translate("MainWindow", "End"))
        self.appTabs.setTabText(self.appTabs.indexOf(self.tabDNS), _translate("MainWindow", "DNS"))
